function errorHandler(){
     try {
         setTimeout(()=>{
              temp
         })
     } catch (error) {
          console.log("by code",error)
     }
}
errorHandler()
//silent fail